spring.application.name=wonders
server.servlet.context-path=/api
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/wonders-of-the-world
spring.datasource.username=postgres
spring.datasource.password=wonders-of-the-world-psswd_1234@!
spring.datasource.driver-class-name=org.postgresql.Driver


# FOR DEVELOPMENT
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# AWS
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.s3.path-style-access-enabled=true