networks:
  wonders-of-the-world-network:
    external: true
  
services:
  wonders-of-the-world:
    container_name: wonders-of-the-world
    image: wonders-of-the-world:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://wonders-of-the-world_db:5432/wonders-of-the-world
      - SPRING_CLOUD_AWS_ENDPOINT=http://localstack:4566 
    depends_on:
      - wonders-of-the-world_db
    ports:
      - "8080:8080"
    networks:
      - wonders-of-the-world-network

  wonders-of-the-world_db:
    container_name: wonders-of-the-world_db
    image: postgres:18.4-alpine
    environment:
      POSTGRES_DB: wonders-of-the-world
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wonders-of-the-world-psswd_1234@!
    volumes:
      - /srv/wonders-of-the-world/wonders-of-the-world_db/dev/postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - wonders-of-the-world-network
